const e = require("fs"), r = require("path"), t = require("rimraf"), i = require("prettier"), o = require("./generateRouteFile"), n = require("./interactiveFileReplacement"), s = require("./config");
module.exports = 
async function({
    destDir: a
}) {
    const u = r.join(a, "src/pages/IceworksPreviewPage");
    t.sync(u);
    const c = r.join(a, "generator.json"), f = JSON.parse(e.readFileSync(c, "utf-8"));
    f.routes = f.routes.filter(e => "IceworksPreviewPage" !== e.path), e.writeFileSync(c, JSON.stringify(f, null, 2) + "\n");
    const g = r.join(a, "src/routes.jsx"), l = new n({
        file: g,
        tagPrefix: "// \x3c!-- auto generated routes start --\x3e",
        tagSuffix: "// \x3c!-- auto generated routes end --\x3e"
    }), {
        routes: p,
        imports: x
    } = await o(a, f.routes);
    l.replace(i.format(`$ {
        x
    }\nconst autoGeneratedRoutes = $ {
        p
    };`, s.prettier))
};